// Generated by CoffeeScript 1.9.3
module.exports = function(grunt) {
  grunt.initConfig({
    concurrent: {
      target: {
        tasks: ['less', 'coffee', 'watch'],
        options: {
          logConcurrentOutput: true
        }
      }
    },
    less: {
      dev: {
        expand: true,
        flatten: true,
        cwd: 'public/style',
        src: ['*.less'],
        dest: 'public/style/dist/',
        ext: '.css'
      }
    },
    coffee: {
      dev: {
        expand: true,
        flatten: true,
        cwd: 'public/js',
        src: ['*.coffee'],
        dest: 'public/js/dist/',
        ext: '.js'
      }
    },
    watch: {
      files: ['public/style/*.less', 'public/js/*.coffee'],
      tasks: ['less', 'coffee']
    }
  });
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-contrib-coffee');
  grunt.loadNpmTasks('grunt-contrib-less');
  grunt.loadNpmTasks('grunt-concurrent');
  return grunt.registerTask("default", function() {
    return console.log(3232);
  });
};
